name: ml_book
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - folium=0.14.0
  - pip
  - pip:
    - ipykernel==6.25.0
    - notebook==7.0.2
